-- Legacy chat storage kept for backward compatibility
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  character_id text not null,
  role text not null check (role in ('user', 'assistant')),
  content jsonb not null check (jsonb_typeof(content) = 'object')
);

create index if not exists idx_chat_messages_user_character_created_desc
  on public.chat_messages (user_id, character_id, created_at desc);

create index if not exists idx_chat_messages_user_created_desc
  on public.chat_messages (user_id, created_at desc);

alter table public.chat_messages enable row level security;

do $$ begin
  create policy "Users can view their own legacy messages"
    on public.chat_messages for select
    using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can insert their own legacy messages"
    on public.chat_messages for insert
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can delete their own legacy messages"
    on public.chat_messages for delete
    using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users on delete cascade,
  display_name text,
  avatar_url text,
  bio text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists bio text;
alter table public.profiles add column if not exists is_owner boolean not null default false;
alter table public.profiles add column if not exists updated_at timestamp with time zone default timezone('utc'::text, now()) not null;

alter table public.profiles enable row level security;

do $$ begin
  create policy "Users can read their own profile"
    on public.profiles for select
    using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can write their own profile"
    on public.profiles for all
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

create table if not exists public.app_settings (
  key text primary key,
  value_json jsonb not null default '{}'::jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create or replace function public.is_owner_user()
returns boolean
language sql
stable
as $$
  with owner_setting as (
    select value_json
    from public.app_settings
    where key = 'owner_user_ids'
    limit 1
  )
  select
    coalesce((select p.is_owner from public.profiles p where p.user_id = auth.uid()), false)
    or exists (
      select 1
      from owner_setting s,
      lateral jsonb_array_elements_text(
        case
          when jsonb_typeof(s.value_json) = 'array' then s.value_json
          when jsonb_typeof(s.value_json) = 'object' and jsonb_typeof(s.value_json -> 'ids') = 'array' then s.value_json -> 'ids'
          else '[]'::jsonb
        end
      ) as owner_id(value)
      where owner_id.value = auth.uid()::text
    );
$$;

create table if not exists public.characters (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid references auth.users on delete cascade not null,
  slug text unique not null,
  name text not null,
  headline text,
  summary text not null default '',
  cover_image_url text,
  avatar_image_url text,
  visibility text not null default 'private' check (visibility in ('private','unlisted','public')),
  display_status text not null default 'draft' check (display_status in ('visible','hidden','draft')),
  source_type text not null default 'original' check (source_type in ('original','derivative')),
  tags text[] not null default '{}',
  profile_json jsonb not null default '{}'::jsonb,
  speech_style_json jsonb not null default '{}'::jsonb,
  prompt_profile_json jsonb not null default '{}'::jsonb,
  favorite_count integer not null default 0,
  chat_start_count integer not null default 0,
  published_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.characters add column if not exists owner_user_id uuid references auth.users on delete cascade;
alter table public.characters add column if not exists slug text;
alter table public.characters add column if not exists name text;
alter table public.characters add column if not exists headline text;
alter table public.characters add column if not exists summary text not null default '';
alter table public.characters add column if not exists cover_image_url text;
alter table public.characters add column if not exists avatar_image_url text;
alter table public.characters add column if not exists visibility text not null default 'private';
alter table public.characters add column if not exists display_status text not null default 'draft';
alter table public.characters add column if not exists source_type text not null default 'original';
alter table public.characters add column if not exists tags text[] not null default '{}';
alter table public.characters add column if not exists profile_json jsonb not null default '{}'::jsonb;
alter table public.characters add column if not exists speech_style_json jsonb not null default '{}'::jsonb;
alter table public.characters add column if not exists prompt_profile_json jsonb not null default '{}'::jsonb;
alter table public.characters add column if not exists favorite_count integer not null default 0;
alter table public.characters add column if not exists chat_start_count integer not null default 0;
alter table public.characters add column if not exists published_at timestamp with time zone;
alter table public.characters add column if not exists updated_at timestamp with time zone default timezone('utc'::text, now()) not null;

create index if not exists idx_characters_owner_updated on public.characters (owner_user_id, updated_at desc);
create index if not exists idx_characters_visible_updated on public.characters (display_status, updated_at desc);

alter table public.characters enable row level security;

do $$ begin
  create policy "Public can read visible characters or owners can read their own"
    on public.characters for select
    using ((visibility = 'public' and display_status = 'visible') or auth.uid() = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can insert their own characters"
    on public.characters for insert
    with check (auth.uid() = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can update their own characters"
    on public.characters for update
    using (auth.uid() = owner_user_id)
    with check (auth.uid() = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Owner users can manage all characters"
    on public.characters for all
    using (public.is_owner_user())
    with check (public.is_owner_user());
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can delete their own characters"
    on public.characters for delete
    using (auth.uid() = owner_user_id or public.is_owner_user());
exception when duplicate_object then null; end $$;

create table if not exists public.worlds (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid references auth.users on delete cascade not null,
  slug text unique not null,
  name text not null,
  headline text,
  summary text not null default '',
  cover_image_url text,
  visibility text not null default 'private' check (visibility in ('private','unlisted','public')),
  display_status text not null default 'draft' check (display_status in ('visible','hidden','draft')),
  source_type text not null default 'original' check (source_type in ('original','derivative')),
  tags text[] not null default '{}',
  world_rules_markdown text,
  prompt_profile_json jsonb not null default '{}'::jsonb,
  favorite_count integer not null default 0,
  chat_start_count integer not null default 0,
  published_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.worlds add column if not exists owner_user_id uuid references auth.users on delete cascade;
alter table public.worlds add column if not exists slug text;
alter table public.worlds add column if not exists name text;
alter table public.worlds add column if not exists headline text;
alter table public.worlds add column if not exists summary text not null default '';
alter table public.worlds add column if not exists cover_image_url text;
alter table public.worlds add column if not exists visibility text not null default 'private';
alter table public.worlds add column if not exists display_status text not null default 'draft';
alter table public.worlds add column if not exists source_type text not null default 'original';
alter table public.worlds add column if not exists tags text[] not null default '{}';
alter table public.worlds add column if not exists world_rules_markdown text;
alter table public.worlds add column if not exists prompt_profile_json jsonb not null default '{}'::jsonb;
alter table public.worlds add column if not exists favorite_count integer not null default 0;
alter table public.worlds add column if not exists chat_start_count integer not null default 0;
alter table public.worlds add column if not exists published_at timestamp with time zone;
alter table public.worlds add column if not exists updated_at timestamp with time zone default timezone('utc'::text, now()) not null;

create index if not exists idx_worlds_owner_updated on public.worlds (owner_user_id, updated_at desc);
create index if not exists idx_worlds_visible_updated on public.worlds (display_status, updated_at desc);

alter table public.worlds enable row level security;

do $$ begin
  create policy "Public can read visible worlds or owners can read their own"
    on public.worlds for select
    using ((visibility = 'public' and display_status = 'visible') or auth.uid() = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can insert their own worlds"
    on public.worlds for insert
    with check (auth.uid() = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can update their own worlds"
    on public.worlds for update
    using (auth.uid() = owner_user_id)
    with check (auth.uid() = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Owner users can manage all worlds"
    on public.worlds for all
    using (public.is_owner_user())
    with check (public.is_owner_user());
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can delete their own worlds"
    on public.worlds for delete
    using (auth.uid() = owner_user_id or public.is_owner_user());
exception when duplicate_object then null; end $$;

create table if not exists public.character_world_links (
  id uuid primary key default gen_random_uuid(),
  character_id uuid references public.characters on delete cascade not null,
  world_id uuid references public.worlds on delete cascade not null,
  owner_user_id uuid references auth.users on delete cascade not null,
  is_recommended boolean not null default true,
  sort_order integer not null default 0,
  link_reason text not null default '',
  default_opening_context text,
  default_relationship_context text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (character_id, world_id)
);

create index if not exists idx_character_world_links_character on public.character_world_links (character_id, sort_order asc, updated_at desc);
create index if not exists idx_character_world_links_world on public.character_world_links (world_id, sort_order asc, updated_at desc);

alter table public.character_world_links enable row level security;

do $$ begin
  create policy "Public can read links when both endpoints are visible or owners can read their own"
    on public.character_world_links for select
    using (
      auth.uid() = owner_user_id
      or exists (
        select 1
        from public.characters c
        join public.worlds w on w.id = character_world_links.world_id
        where c.id = character_world_links.character_id
          and c.visibility = 'public'
          and c.display_status = 'visible'
          and w.visibility = 'public'
          and w.display_status = 'visible'
      )
    );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can insert their own links"
    on public.character_world_links for insert
    with check (auth.uid() = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can update their own links"
    on public.character_world_links for update
    using (auth.uid() = owner_user_id)
    with check (auth.uid() = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Owner users can manage all links"
    on public.character_world_links for all
    using (public.is_owner_user())
    with check (public.is_owner_user());
exception when duplicate_object then null; end $$;

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users on delete cascade not null,
  character_id uuid references public.characters on delete cascade not null,
  world_id uuid references public.worlds on delete set null,
  character_world_link_id uuid references public.character_world_links on delete set null,
  user_alias text not null default '나',
  title text not null,
  bridge_profile_json jsonb not null default '{}'::jsonb,
  resolved_prompt_snapshot_json jsonb not null default '{}'::jsonb,
  last_message_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_rooms_user_updated on public.rooms (user_id, updated_at desc);

alter table public.rooms enable row level security;

do $$ begin
  create policy "Users can read their own rooms"
    on public.rooms for select
    using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can insert their own rooms"
    on public.rooms for insert
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can update their own rooms"
    on public.rooms for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

create table if not exists public.room_messages (
  id uuid primary key default gen_random_uuid(),
  room_id uuid references public.rooms on delete cascade not null,
  role text not null check (role in ('user','assistant')),
  content_json jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_room_messages_room_created on public.room_messages (room_id, created_at asc);

alter table public.room_messages enable row level security;

do $$ begin
  create policy "Users can read messages in their own rooms"
    on public.room_messages for select
    using (exists (select 1 from public.rooms where rooms.id = room_messages.room_id and rooms.user_id = auth.uid()));
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can insert messages in their own rooms"
    on public.room_messages for insert
    with check (exists (select 1 from public.rooms where rooms.id = room_messages.room_id and rooms.user_id = auth.uid()));
exception when duplicate_object then null; end $$;

create table if not exists public.room_state_summaries (
  room_id uuid primary key references public.rooms on delete cascade,
  current_situation text,
  location text,
  relationship_state text,
  inventory_json jsonb not null default '[]'::jsonb,
  appearance_json jsonb not null default '[]'::jsonb,
  pose_json jsonb not null default '[]'::jsonb,
  future_promises_json jsonb not null default '[]'::jsonb,
  world_notes_json jsonb not null default '[]'::jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.room_state_summaries enable row level security;

do $$ begin
  create policy "Users can read room state summaries in their own rooms"
    on public.room_state_summaries for select
    using (exists (select 1 from public.rooms where rooms.id = room_state_summaries.room_id and rooms.user_id = auth.uid()));
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can write room state summaries in their own rooms"
    on public.room_state_summaries for all
    using (exists (select 1 from public.rooms where rooms.id = room_state_summaries.room_id and rooms.user_id = auth.uid()))
    with check (exists (select 1 from public.rooms where rooms.id = room_state_summaries.room_id and rooms.user_id = auth.uid()));
exception when duplicate_object then null; end $$;

create table if not exists public.bookmarks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users on delete cascade not null,
  target_type text not null check (target_type in ('character','world')),
  target_id uuid not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create unique index if not exists idx_bookmarks_user_target_unique on public.bookmarks (user_id, target_type, target_id);

alter table public.bookmarks enable row level security;

do $$ begin
  create policy "Users can manage their own bookmarks"
    on public.bookmarks for all
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

create table if not exists public.recent_views (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users on delete cascade not null,
  target_type text not null check (target_type in ('character','world')),
  target_id uuid not null,
  viewed_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_recent_views_user_viewed on public.recent_views (user_id, viewed_at desc);

alter table public.recent_views enable row level security;

do $$ begin
  create policy "Users can manage their own recent views"
    on public.recent_views for all
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

create table if not exists public.character_assets (
  id uuid primary key default gen_random_uuid(),
  character_id uuid references public.characters on delete cascade not null,
  asset_kind text not null check (asset_kind in ('thumb','card','detail','gallery')),
  url text not null,
  width integer,
  height integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_character_assets_character_kind on public.character_assets (character_id, asset_kind);

alter table public.character_assets enable row level security;

do $$ begin
  create policy "Public can read assets of visible public characters or owners can read their own"
    on public.character_assets for select
    using (
      exists (
        select 1 from public.characters c
        where c.id = character_assets.character_id
          and ((c.visibility = 'public' and c.display_status = 'visible') or c.owner_user_id = auth.uid())
      )
    );
exception when duplicate_object then null; end $$;

create table if not exists public.world_assets (
  id uuid primary key default gen_random_uuid(),
  world_id uuid references public.worlds on delete cascade not null,
  asset_kind text not null check (asset_kind in ('thumb','card','hero','gallery')),
  url text not null,
  width integer,
  height integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_world_assets_world_kind on public.world_assets (world_id, asset_kind);

alter table public.world_assets enable row level security;

do $$ begin
  create policy "Public can read assets of visible public worlds or owners can read their own"
    on public.world_assets for select
    using (
      exists (
        select 1 from public.worlds w
        where w.id = world_assets.world_id
          and ((w.visibility = 'public' and w.display_status = 'visible') or w.owner_user_id = auth.uid())
      )
    );
exception when duplicate_object then null; end $$;

create table if not exists public.app_settings (
  key text primary key,
  value_json jsonb not null default '{}'::jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.app_settings add column if not exists value_json jsonb not null default '{}'::jsonb;
alter table public.app_settings add column if not exists updated_at timestamp with time zone default timezone('utc'::text, now()) not null;
alter table public.app_settings enable row level security;

do $$ begin
  create policy "Public can read app settings"
    on public.app_settings for select
    using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Owner users can write app settings"
    on public.app_settings for all
    using (public.is_owner_user())
    with check (public.is_owner_user());
exception when duplicate_object then null; end $$;

insert into public.app_settings (key, value_json)
values ('owner_user_ids', '[]'::jsonb)
on conflict (key) do nothing;

insert into public.app_settings (key, value_json)
values ('home.hero', jsonb_build_object('mode', 'auto', 'targetPath', '/characters/mika'))
on conflict (key) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'vmate-assets',
  'vmate-assets',
  true,
  8388608,
  array['image/png', 'image/jpeg', 'image/webp', 'image/avif']
)
on conflict (id) do nothing;

do $$ begin
  create policy "Public can read vmate assets"
    on storage.objects for select
    using (bucket_id = 'vmate-assets');
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Authenticated users can upload vmate assets to their own folder"
    on storage.objects for insert
    with check (
      bucket_id = 'vmate-assets'
      and split_part(name, '/' , 1) = auth.uid()::text
    );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Authenticated users can update vmate assets in their own folder"
    on storage.objects for update
    using (
      bucket_id = 'vmate-assets'
      and split_part(name, '/' , 1) = auth.uid()::text
    )
    with check (
      bucket_id = 'vmate-assets'
      and split_part(name, '/' , 1) = auth.uid()::text
    );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Authenticated users can delete vmate assets in their own folder"
    on storage.objects for delete
    using (
      bucket_id = 'vmate-assets'
      and split_part(name, '/' , 1) = auth.uid()::text
    );
exception when duplicate_object then null; end $$;
